group_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('group_works.urls')),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
#     path('password-reset-complete/',
#          auth_views.PasswordResetCompleteView.as_view(
#              template_name='users/password_reset_complete.html'),
#          name='password_reset_complete'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group_works/urls.py
'''
Created on Jul 8, 2020

@author: rb18s
'''

"""Defines URL patterns for group_works."""

from django.urls import path

from .views import (
    ProjectListView,
    TaskListView,
    TaskDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ProjectCompleteView,
    TaskCompleteView,
    )
from . import views

app_name = 'group_works'
urlpatterns = [
    path('', views.home, name='home'),
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('projects/new', ProjectCreateView.as_view(), name='project-create'),
    path('projects/<int:project_pk>/', TaskListView.as_view(),
         name='task-list'),
    path('projects/<int:project_pk>/update',
        ProjectUpdateView.as_view(), name='project-update'),
    path('projects/<int:project_pk>/task/new',
         TaskCreateView.as_view(), name='task-create'),
    path('task/<int:task_pk>/',
         TaskDetailView.as_view(), name='task-detail'),
    path('task/<int:task_pk>/update',
         TaskUpdateView.as_view(), name='task-update'),
    path('projects/<int:project_pk>/delete/',
         ProjectDeleteView.as_view(), name='project-delete'),
    path('task/<int:task_pk>/delete/',
         TaskDeleteView.as_view(), name='task-delete'),
    path('projects/<int:project_pk>/complete/', ProjectCompleteView.as_view(),
         name='project-complete'),
    path('task/<int:task_pk>/complete/', TaskCompleteView.as_view(),
         name='task-complete'),
    path('about/', views.about, name='about'),

    ]

users/urls.py
'''
Created on Jul 10, 2020

@author: rb18s
'''

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [

    ]

group_works/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse

# Create your models here.


class Project(models.Model):
    """A project the user is collaborating on."""
    title = models.CharField(max_length=100)
    last_edit = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()  # use a DateInput widget
    description = models.TextField(default='No Description.')
    complete = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # collaborators =

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

    def get_absolute_url(self):
        return reverse('group_works:task-list', kwargs={'project_pk':self.pk})


class Task(models.Model):
    """A task to be completed for a project."""
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    last_edit = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()
    complete = models.BooleanField(default=False)
    description = models.TextField(default='No Description.')

    # collaborators =

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

    def get_absolute_url(self):
        return reverse('group_works:task-detail', kwargs={'task_pk':self.pk})

group_works/forms.py
'''
Created on Jul 10, 2020

@author: rb18s
'''

from django import forms

from .models import Project, Task


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['title', 'due_date', 'description']
        labels = {'title': 'Title', 'due_date': 'Due Date',
                  'description': 'Describe your project:'}
        widgets = {'due_date': forms.DateInput(),
                   'description': forms.Textarea(attrs={'cols': 80})}
        # add a datepicker calender widget


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'due_date', 'description']
        labels = {'title': 'Title', 'due_date': 'Due Date',
                  'description': 'Describe the task:'}
        widgets = {'description': forms.Textarea(attrs={'cols': 80})}


class ProjectDeleteForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = []


class TaskDeleteForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = []


class ProjectCompleteForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = []


class TaskCompleteForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = []

group_works/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
# from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Project, Task
from .forms import ProjectForm, TaskForm, ProjectDeleteForm, TaskDeleteForm


def home(request):
    """The home page for Group Work."""
    return render(request, 'group_works/home.html')


class ProjectListView(ListView):
    model = Project
    template_name = 'group_works/project-list.html'
    context_object_name = 'projects'
    ordering = ['due_date']
    paginate_by = 5

    def get_queryset(self):
        return Project.objects.filter(owner=self.request.user).order_by('due_date')


class TaskListView(ListView):
    model = Task
    template_name = 'group_works/task-list.html'
    context_object_name = 'tasks'
    ordering = ['due_date']
    paginate_by = 5

    def get_queryset(self):
        proj = get_object_or_404(Project, pk=self.kwargs['project_pk'])
        return Task.objects.filter(project=proj).order_by('due_date')

    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.filter(
            pk=self.kwargs['project_pk']).get()
        return context


class TaskDetailView(DetailView):
    model = Task
    pk_url_kwarg = 'task_pk'


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['title', 'due_date', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['title', 'due_date', 'description']
    pk_url_kwarg = 'project_pk'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.owner:
            return True
        return False


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
#     success_url = 'project-list'
    pk_url_kwarg = 'project_pk'

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.owner:
            return True
        return False

    def get_success_url(self):
#         project = self.object.project
        return reverse_lazy('group_works:project-list')


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'due_date', 'description']

    def form_valid(self, form):
        form.instance.project = Project.objects.get(pk=self.kwargs['project_pk'])
        form.instance.project.owner = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    fields = ['title', 'due_date', 'description']
    pk_url_kwarg = 'task_pk'

    def form_valid(self, form):
        form.instance.project.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        if self.request.user == task.project.owner:
            return True
        return False


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Task
    pk_url_kwarg = 'task_pk'

    def test_func(self):
        task = self.get_object()
        if self.request.user == task.project.owner:
            return True
        return False

    def get_success_url(self):
        project = self.object.project
        return reverse_lazy('group_works:task-list', kwargs={'project_pk': project.pk})


class ProjectCompleteView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = []
    pk_url_kwarg = 'project_pk'
    template_name_suffix = '_complete'

    def form_valid(self, form):
        form.instance.complete = not form.instance.complete
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.owner:
            return True
        return False


class TaskCompleteView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    fields = []
    pk_url_kwarg = 'task_pk'
    template_name_suffix = '_complete'

    def form_valid(self, form):
        form.instance.complete = not form.instance.complete
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        if self.request.user == task.project.owner:
            return True
        return False


def about(request):
    return render(request, 'group_works/about.html', {'title': 'About'})

# def __check_project_owner__(owner, user):
#     """Check if the user has access to a page.
#     Raise a 404 error if not."""
#     if owner != user:
#         raise Http404

# @login_required
# def projects(request):
#     """Show all projects."""
#     projects = Project.objects.filter(owner=request.user).order_by('due_date')
#     context = {'projects': projects}
#     return render(request, 'group_works/projects.html', context)

# @login_required
# def project(request, project_id):
#     """Show all tasks for requested project."""
#     project = get_object_or_404(Project, id=project_id)
#     # Make sure topic belongs to current user
#     __check_project_owner__(project.owner, request.user)
#
#     tasks = project.task_set.order_by('due_date')
#     context = {'project': project, 'tasks': tasks}
#     return render(request, 'group_works/project.html', context)

# @login_required
# def task(request, task_id):
#     """Show info for a task."""
#     task = get_object_or_404(Task, id=task_id)
#     project = task.project
#     __check_project_owner__(project.owner, request.user)
#
#     context = {'task': task, 'project': project}
#     return render(request, 'group_works/task.html', context)

# @login_required
# def new_project(request):
#     """Add a new project."""
#     if request.method != 'POST':
#         form = ProjectForm()
#     else:
#         form = ProjectForm(data=request.POST)
#         if form.is_valid():
#             new_project = form.save(commit=False)
#             new_project.owner = request.user
#             new_project.save()
#             return redirect('group_works:projects')  # in the future i want this to redirect to the new project page
#
#     context = {'form': form}
#     return render(request, 'group_works/new_project.html', context)

# @login_required
# def edit_project(request, project_id):
#     """Edit an existing project."""
#     project = Project.objects.get(id=project_id)
#     __check_project_owner__(project.owner, request.user)
#
#     if request.method != 'POST':
#         form = ProjectForm(instance=project)
#     else:
#         form = ProjectForm(instance=project, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('group_works:project', project_id=project.id)
#
#     context = {'project': project, 'form': form}
#     return render(request, 'group_works/edit_project.html', context)

# @login_required
# def new_task(request, project_id):
#     """Add a new task."""
#     project = Project.objects.get(id=project_id)
#     __check_project_owner__(project.owner, request.user)
#
#     if request.method != 'POST':
#         form = TaskForm()
#     else:
#         form = TaskForm(data=request.POST)
#         if form.is_valid():
#             new_task = form.save(commit=False)
#             new_task.project = project
#             new_task.save()
#             return redirect('group_works:project', project_id=project_id)
#
#     context = {'project': project, 'form': form}
#     return render(request, 'group_works/new_task.html', context)
#
#
# @login_required
# def edit_task(request, task_id):
#     """Edit an existing task."""
#     task = Task.objects.get(id=task_id)
#     project = task.project
#     __check_project_owner__(project.owner, request.user)
#
#     if request.method != 'POST':
#         form = TaskForm(instance=task)
#     else:
#         form = TaskForm(instance=task, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('group_works:project', project_id=project.id)
#
#     context = {'task': task, 'project': project, 'form': form}
#     return render(request, 'group_works/edit_task.html', context)
#
#
# @login_required
# def delete_project(request, project_id):
#     project = Project.objects.get(id=project_id)
#     __check_project_owner__(project.owner, request.user)
#
#     if request.method != 'POST':
#         form = ProjectDeleteForm(instance=project)
#     else:
#         form = ProjectDeleteForm(instance=project, data=request.POST)
#         if form.is_valid():
#             project.delete()
#             return redirect('group_works:projects')
#
#     context = {'project': project, 'form': form}
#     return render(request, 'group_works/delete_project.html', context)
#
#
# @login_required
# def delete_task(request, task_id):
#     task = Task.objects.get(id=task_id)
#     project = task.project
#     __check_project_owner__(project.owner, request.user)
#
#     if request.method != 'POST':
#         form = TaskDeleteForm(instance=task)
#     else:
#         form = TaskDeleteForm(instance=task, data=request.POST)
#         if form.is_valid():
#             task.delete()
#             print('deleted')
#             return redirect('group_works:project', project_id=project.id)
#
#     context = {'task': task, 'project': project, 'form': form}

group_works/templates/group_works/about.html
{% extends "group_works/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<h2>About</h2>
{% endblock page_header %}

group_works/templates/group_works/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'group_works/main.css' %}">

		<title>Groups Work</title>
		
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'group_works:home' %}">Groups Work</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'group_works:home' %}">Home</a>
							{% if user.is_authenticated %}
								<a class="nav-item nav-link" href="{% url 'group_works:project-list' %}">Projects</a>
								<a class="nav-item nav-link" href="{% url 'group_works:project-create' %}">New Project</a>
							{% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
					{% block content %}{% endblock content %}
        </div>
        <div class="col-md-4 ">
					<div class="hidden-sidebar" display: hidden>
						<h3>Our Sidebar</h3>
						<p class='text-muted'>You can put any information here you'd like.
							<ul class="list-group">
								<li class="list-group-item list-group-item-light">Latest Posts</li>
								<li class="list-group-item list-group-item-light">Announcements</li>
								<li class="list-group-item list-group-item-light">Calendars</li>
								<li class="list-group-item list-group-item-light">etc</li>
							</ul>
						</p>
					</div>
				</div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

group_works/templates/group_works/home.html
{% extends "group_works/base.html" %}

{% block content %}
	<article class="media content-section">
		<div class="media-body">
			<div class="jumbotron">
				<h1 class="display-3">Streamline your projects.</h1>
				<p class="lead">Keep your team organized and focused with our 
						simple group management system.</p>
				{% if user.is_authenticated %}
					<h4>Welcome, {{ user.username }}.</h4>
				{% else %}
					<a class="btn btn-lg btn-primary" href="{% url 'register' %}"
							role="button">Register &raquo;</a>
					<p class="content-info"><br>If you would like to explore Groups Work without
					creating an account, please sign in with the following:<br>
					username: testuser<br>
					password: test4321<br>
					Note that any changes you make will be viewable by 
					others who use this account.</p>
				{% endif %}
			</div>
		</div>
	</article>
{% endblock content %}

group_works/templates/group_works/project_confirm_delete.html
{% extends "group_works/base.html" %}

{% block content %}

	<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Delete Project</legend>
							<h2>Are you sure you want to delete project "{{ project.title }}"?</h2>
						</fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
								<a class="btn btn-outline-secondary" href="{% url 'group_works:task-list' project.pk %}">Cancel</a>
            </div>
        </form>
    </div>
	
{% endblock content %}

group_works/templates/group_works/project_form.html
{% extends "group_works/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Project</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add Project</button>
            </div>
        </form>
    </div>
	
{% endblock content %}

group_works/templates/group_works/project_list.html
{% extends "group_works/base.html" %}

{% block content %}
	<h2 class="page-title">Projects</h2>
	<h5>
		<a class="content-info" href="{%url 'group_works:project-create' %}">Add a new project</a>
	</h5>

	{% for project in projects %}
		<article class="media content-section">
			<img class="rounded-circle creator-img" src="{{ project.owner.profile.image.url }}">
			<div class="media-body">
				<div class="page-metadata">
					<p class="text-secondary" >{{project.owner}}<br>
						{{project.due_date|date:'M d, Y' }}</p>
				</div>
				<p>
					<a class="page-content" href="{%url 'group_works:task-list' project.pk %}">{{ project.title }}</a>
				</p>
			</div>
		</article>
	{% empty %}
		<article class="media content-section">
			<p>
				<a class="page-content">You don't have any projects.</a>
			</p>
		</article>
	{% endfor %}
	{% if is_paginated %}
	
		{% if page_obj.has_previous %}
			{% if page_obj.previous_page_number != 1 %}
				<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			{% endif %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
		
		{% for num in page_obk.paginator.page_range %}
		
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
				{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'-3' %}
					<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
			
		{% endfor %}
		
		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
			{% if page_obj.next_page_number != page_obj.paginator.num_pages %}
				<a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages }}">Last</a>
			{% endif %}
		{% endif %}	
		
	{% endif %}
{% endblock content %}

group_works/templates/group_works/projects.html
{% extends "group_works/base.html" %}

{% block page_header %}
	<h2 class="page-title">Projects</h2>
	<h5>
		<a class="content-info" href="{%url 'group_works:new_project' %}">Add a new project</a>
	</h5>
{% endblock page_header %}

{% block content %}
		{% for project in projects %}
			<article class="media content-section">
				<img class="rounded-circle creator-img" src="{{ project.owner.profile.image.url }}">
				<div class="media-body">
					<div class="page-metadata">
						<p class="text-secondary" >{{project.owner}}<br>
							{{project.due_date|date:'M d, Y' }}</p>
					</div>
					<p>
						<a class="page-content" href="{%url 'group_works:project' project.id %}">{{ project }}</a>
					</p>
				</div>
			</article>
		{% empty %}
			<article class="media content-section">
				<p>
					<a class="page-content">You don't have any projects.</a>
				</p>
			</article>
		{% endfor %}
{% endblock content %}

group_works/templates/group_works/task_confirm_delete.html
{% extends "group_works/base.html" %}

{% block content %}

	<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Delete Task</legend>
							<h2>Are you sure you want to delete task "{{ task.title }}"?</h2>
						</fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
								<a class="btn btn-outline-secondary" href="{% url 'group_works:task-detail' task.pk %}">Cancel</a>
            </div>
        </form>
    </div>
	
{% endblock content %}

group_works/templates/group_works/task_detail.html
{% extends "group_works/base.html" %}

{% block content %}
	<h2>
		<a class="page-title" href="{% url 'group_works:task-list' task.project.pk %}">{{ task.project.title }}</a>
	</h2>
	<h3 class="secondary-title">{{ task.title }}</h3>
	<a class="content-info" href="{%url 'group_works:task-update' task.pk %}">Edit Task</a>
	<a class="content-info" href="{%url 'group_works:task-delete' task.pk %}">Delete Task</a>

	<h6 class="content-info">Due: {{task.due_date|date:'M d, Y' }}</h6>

	<h4 class="content-header">Description:</h4>
	<p class="page-content">{{task.description|linebreaks}}</p>

	
{% endblock content %}

group_works/templates/group_works/task_form.html
{% extends "group_works/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

	<h2>
		<a class="page-title" href="#">{{ project.title }}</a>
	</h2>
	
	    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Task</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add Task</button>
            </div>
        </form>
    </div>
	
{% endblock content %}

group_works/templates/group_works/task_list.html
{% extends "group_works/base.html" %}
{% load bootstrap4 %}


{% block content %}

	<div>
		<h2 class="page-title" style="display: inline-block">{{ project.title }}</h2>
		{% if project.complete %}
				<span class="badge badge-success float-right">Complete</span>
		{% else %}
				<span class="vertical-center badge badge-info float-right">Due: {{ project.due_date|date:'M d, Y' }}</span>
		{% endif %}
	</div>
	<br>
	<div class="container">
		<div class="row">
			<div class="col-sm">
				<a class="btn btn-warning" href="{%url 'group_works:project-update' project.pk %}">Edit Project</a>
			</div>
			<div class="col-sm">
				<a class="btn btn-danger" href="{%url 'group_works:project-delete' project.pk %}">Delete Project</a>
			</div>
			{% if project.complete %}
			<div class="col-sm">
				<a class="btn btn-primary" href="{%url 'group_works:project-complete' project.pk %}">Mark Incomplete</a>
			</div>
			{% else %}
			<div class="col-sm">
				<a class="btn btn-success" href="{%url 'group_works:project-complete' project.pk %}">Mark Complete</a>
			</div>
			{% endif %}
		</div>
	</div>
	<br>
	<article class="media content-section">
		<h5 class="content-description">{{ project.description }}</h5>
	</article>	
	<hr>
	<h4 class="content-header">Tasks:</h4>

	<a class="content-info" href="{%url 'group_works:task-create' project.pk %}">Add Task</a>


	{% for task in tasks %}
		<article class="media content-section">
			<div class="media-body">
				<p class="text-secondary">
					{{task.due_date|date:'M d, Y' }}
				</p>
				<p>
					<a class="page-content" href="{% url 'group_works:task-detail' task.pk %}">
						{{ task.title }}
					</a>
				<p>
			</div>
		</article>
	{% empty %}
		<article class="media content-section">
			<div class="media-body">
				<h6 class="page-content">There are no tasks for this project yet.</h6>
			</div>
		</article>
	{% endfor %}
	
	{% if is_paginated %}
	
		{% if page_obj.has_previous %}
			{% if page_obj.previous_page_number != 1 %}
				<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			{% endif %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
		
		{% for num in page_obk.paginator.page_range %}
		
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
				{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'-3' %}
					<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
			
		{% endfor %}
		
		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
			{% if page_obj.next_page_number != page_obj.paginator.num_pages %}
				<a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages }}">Last</a>
			{% endif %}
		{% endif %}	
		
	{% endif %}

	
{% endblock content %}